#!/usr/bin/env python3
"""Regenerate main/icon.h from source PNGs.

The library menu icons are 8-bit grayscale dumps (0=black, 255=white) plus
a matching alpha mask, blitted 1:1 into the 8-bit menu sprite with alpha
blending over the card background. Grayscale (not 1-bit) preserves
the fonts' antialiasing, which is what makes them look smooth on EPD.

Each source is autocropped to its opaque content, padded, and fitted to
ICON_SIZE (alpha preserved, NOT flattened):

    python3 tools/convert_icons.py <bookmarks.png> <files.png>

Requires: Pillow
"""
import sys

from PIL import Image

ICON_SIZE = 128
PAD = 10  # padding (source pixels) around the cropped glyph

HEADER = """#pragma once
// Library menu icons: 8-bit grayscale (0=black, 255=white) + alpha mask,
// blitted with blending over the card background.
// Regenerated by tools/convert_icons.py - do not hand-edit.
#include "compat.h"
#define ICON_SIZE %d
""" % ICON_SIZE


def convert(path):
    im = Image.open(path).convert("RGBA")
    bbox = im.split()[3].getbbox()
    if not bbox:
        raise ValueError(f"fully transparent: {path}")
    l, t, r, b = bbox
    l = max(0, l - PAD)
    t = max(0, t - PAD)
    r = min(im.width, r + PAD)
    b = min(im.height, b + PAD)
    im = im.crop((l, t, r, b))
    scale = ICON_SIZE / max(im.width, im.height)
    im = im.resize((max(1, round(im.width * scale)),
                    max(1, round(im.height * scale))), Image.LANCZOS)
    canvas = Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))
    canvas.paste(im, ((ICON_SIZE - im.width) // 2,
                      (ICON_SIZE - im.height) // 2), im)
    return canvas


def emit(name, rgba):
    # Raw luminance (NOT flattened): edge pixels keep art color, coverage
    # lives in alpha, so blit math is a single over-operation.
    gray = list(rgba.convert("L").getdata())
    alpha = list(rgba.split()[3].getdata())
    assert len(gray) == len(alpha) == ICON_SIZE * ICON_SIZE

    def table(suffix, vals):
        rows = []
        for y in range(ICON_SIZE):
            row = ", ".join(f"0x{v:02x}"
                            for v in vals[y * ICON_SIZE:(y + 1) * ICON_SIZE])
            rows.append("    " + row)
        return (f"static const unsigned char PROGMEM {name}{suffix}[] = {{\n" +
                ",\n".join(rows) + "\n};\n")

    return table("", gray) + "\n" + table("_alpha", alpha)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    out = [HEADER]
    for path, name in ((sys.argv[1], "icon_bookmarks_128"),
                       (sys.argv[2], "icon_files_128")):
        rgba = convert(path)
        out.append(emit(name, rgba))
        edge = sum(1 for v in rgba.split()[3].getdata() if 0 < v < 255)
        print(f"{name}: {rgba.size}, blend-edge px: {edge}")
    with open("main/icon.h", "w") as f:
        f.write("\n".join(out))
    print("wrote main/icon.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
